CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    country VARCHAR(255),
    public_profile BOOLEAN DEFAULT FALSE,
    phone_number VARCHAR(20),
    image VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS countries (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    alpha2 VARCHAR(2) NOT NULL,
    alpha3 VARCHAR(3) NOT NULL,
    region VARCHAR(255)
);
